name: Pack Check
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build --configuration Debug
        working-directory: azure-function-redis-binding

      - name: Test
        run: |
          dotnet test --logger "trx;LogFileName=test-results.trx"
        working-directory: azure-function-redis-binding-tests

      - name: Report
        uses: dorny/test-reporter@v1
        with:
          name: Test Report
          path: azure-function-redis-binding-tests/TestResults/test-results.trx
          reporter: dotnet-trx
          list-suites: 'failed'
          list-tests: 'all'
          max-annotations: 50
          fail-on-error: false

      - name: Pack
        run: dotnet pack -c Release --output "./" /p:Version=0.0.1
        working-directory: azure-function-redis-binding