name: Pack Check
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Test
        run: dotnet test
        working-directory: azure-function-redis-binding-tests

      - name: Report
        uses: dorny/test-reporter@v1
        with:
          name: Test Report
          path: azure-function-redis-binding-tests/TestResults
          reporter: xunit
          list-suites: true
          list-tests: true
          max-annotations: 50
          fail-on-error: false

      - name: Pack
        run: dotnet pack -c Release --output "./" /p:Version=0.0.1
        working-directory: azure-function-redis-binding