name: Azure Function Redis Binding Dev
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to associate with the release
        required: true

permissions:
  packages: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Pack
        run: dotnet pack -c Debug -o ./artifact /p:Version=${{ github.event.inputs.version }}

      - name: Publish
        run: |
          dotnet nuget push "artifact/Farrellsoft.Azure.Functions.Extensions.Redis.${{ github.event.inputs.version }}.nupkg"  \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source ""https://nuget.pkg.github.com/farrellsoft/index.json""