name: Redis Binding NuGet Publish
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
        
      - name: Test
        run: |
          dotnet test --logger "trx;LogFileName=test-results.trx"
        working-directory: azure-function-redis-binding-tests

      - name: Report
        uses: dorny/test-reporter@v1
        with:
          name: Test Report
          path: azure-function-redis-binding-tests/TestResults/test-results.trx
          reporter: dotnet-trx
          list-suites: 'failed'
          list-tests: 'all'
          max-annotations: 50
          fail-on-error: false

      - name: Pack
        run: dotnet pack -c Release --output "./" /p:Version=${{ github.ref_name }}
        working-directory: azure-function-redis-binding

      - name: Publish
        run: |
          dotnet nuget push "Farrellsoft.Azure.Functions.Extensions.Redis.${{ github.ref_name }}.nupkg" \
            --api-key ${{ secrets.NUGET_TOKEN }} \
            --source https://api.nuget.org/v3/index.json
        working-directory: azure-function-redis-binding