name: Redis Binding NuGet Publish
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Pack
        run: dotnet pack -c Release --output "./" /p:Version=${{ github.ref_name }}
        working-directory: azure-function-redis-binding

      - name: Publish
        run: |
          dotnet nuget push "Farrellsoft.Azure.Functions.Extensions.Redis.${{ github.ref_name }}.nupkg" -\
            -api-key ${{ secrets.NUGET_TOKEN }} \
            --source https://api.nuget.org/v3/index.json
        working-directory: azure-function-redis-binding